import os

PREFIX = "PREFIX"
TOKEN = "DISCORD TOKEN"
LAVALINK_PASSWORD = "LAVALINK PASSWORD"
OWNER_ID = 80967066455678509
SPOTIFY_CLIENT_ID = "CLIENT ID"
SPOTIFY_CLIENT_SECRET = "CLIENT SECRET"
GENIUS_ACCESS_TOKEN = "ACCESS TOKEN"